import Foundation

package enum BuildInfoVersionResolver {
    package static let environmentKey = "XCODE_MCP_BUILD_VERSION"

    package static func resolve(
        environment: [String: String],
        packageDirectory: URL,
        gitDescribe: (URL) throws -> String? = defaultGitDescribe(in:)
    ) -> String {
        if let version = normalized(environment[environmentKey]) {
            return version
        }

        if let version = try? gitDescribe(packageDirectory),
           let normalizedVersion = normalized(version)
        {
            return normalizedVersion
        }

        return "dev"
    }

    package static func generatedSource(version: String) -> String {
        """
        // Generated by ProxyBuildInfoTool. Do not edit.

        enum ProxyBuildGeneratedInfo {
            static let version = "\(escapedStringLiteral(version))"
        }
        """
    }

    package static func normalized(_ value: String?) -> String? {
        guard let raw = value?.trimmingCharacters(in: .whitespacesAndNewlines), !raw.isEmpty else {
            return nil
        }
        return raw
    }

    package static func defaultGitDescribe(in packageDirectory: URL) throws -> String? {
        let process = Process()
        let outputPipe = Pipe()

        process.executableURL = URL(fileURLWithPath: "/usr/bin/git")
        process.arguments = [
            "-C", packageDirectory.path,
            "describe",
            "--tags",
            "--always",
            "--dirty",
        ]
        process.standardOutput = outputPipe
        process.standardError = Pipe()

        try process.run()
        process.waitUntilExit()

        guard process.terminationStatus == 0 else {
            return nil
        }

        let data = outputPipe.fileHandleForReading.readDataToEndOfFile()
        return String(data: data, encoding: .utf8)
    }

    private static func escapedStringLiteral(_ value: String) -> String {
        value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
    }
}
